// Generated by CoffeeScript 1.7.1
(function() {
  var Digester, crypto;

  crypto = require('crypto');

  module.exports = Digester = (function() {
    function Digester(config, obj) {
      var _ref;
      this.config = config;
      this.obj = obj;
      _ref = this.config, this.base_url = _ref.base_url, this.api_id = _ref.api_id, this.api_secret = _ref.api_secret;
      this.time_of_signing = new Date().getTime();
      this.url = "" + this.base_url + (this.path()) + "?" + (this.vars()) + "&api_mac=" + (this.digest());
    }

    Digester.prototype.path = function() {
      return "/page/api/" + this.obj.service;
    };

    Digester.prototype.vars = function() {
      return ["api_ver=2", "api_id=" + this.api_id, "api_ts=" + this.time_of_signing].concat(this.obj.vars || []).join('&');
    };

    Digester.prototype.digest = function() {
      return crypto.createHmac('sha1', this.api_secret).update(this.signature()).digest('hex');
    };

    Digester.prototype.signature = function() {
      return [this.api_id, this.time_of_signing, this.path(), this.vars()].join('\n');
    };

    return Digester;

  })();

}).call(this);
