// Generated by CoffeeScript 1.7.1
(function() {
  var BSD, Requester, _;

  _ = require('underscore');

  Requester = require('./requester');

  module.exports = BSD = (function() {
    function BSD(options) {
      this.requester = new Requester(options);
    }

    BSD.prototype.get_signup = function(id) {
      return this.requester.get({
        service: 'signup/get_form',
        vars: ["signup_form_id=" + id]
      });
    };

    BSD.prototype.process_signup = function(id, fields) {
      return this.requester.post({
        service: 'signup/process_signup',
        data: {
          signup_form: {
            id: id,
            signup_form_field: this.xml_fields(fields)
          }
        }
      });
    };

    BSD.prototype.xml_fields = function(fields) {
      return _.map(fields, function(obj) {
        obj['$t'] = obj.value;
        delete obj.value;
        return obj;
      });
    };

    return BSD;

  })();

}).call(this);
